drop table if exists class;
drop table if exists register;
drop table if exists school;
drop table if exists student;
drop table if exists subject;
create table class (id integer not null, code varchar(100) not null, classDesc varchar(1000), schoolId integer, primary key (id)) engine=InnoDB;
create table register (subjectId integer not null, studentId integer not null, score double precision, primary key (subjectId, studentId)) engine=InnoDB;
create table school (id integer not null, schoolDesc varchar(1000), name varchar(100) not null, primary key (id)) engine=InnoDB;
create table student (id integer not null, classId integer, mobile varchar(100), name varchar(100) not null, primary key (id)) engine=InnoDB;
create table subject (id integer not null, domain varchar(20), subjectDesc varchar(100), name varchar(100) not null, primary key (id)) engine=InnoDB;
drop table if exists class;
drop table if exists register;
drop table if exists school;
drop table if exists student;
drop table if exists subject;
create table class (id integer not null, code varchar(100) not null, classDesc varchar(1000), schoolId integer, primary key (id)) engine=InnoDB;
create table register (subjectId integer not null, studentId integer not null, score double precision, primary key (subjectId, studentId)) engine=InnoDB;
create table school (id integer not null, schoolDesc varchar(1000), name varchar(100) not null, primary key (id)) engine=InnoDB;
create table student (id integer not null, classId integer, mobile varchar(100), name varchar(100) not null, primary key (id)) engine=InnoDB;
create table subject (id integer not null, domain varchar(20), subjectDesc varchar(100), name varchar(100) not null, primary key (id)) engine=InnoDB;
drop table if exists class;
drop table if exists register;
drop table if exists school;
drop table if exists student;
drop table if exists subject;
create table class (id integer not null, code varchar(100) not null, classDesc varchar(1000), schoolId integer, primary key (id)) engine=InnoDB;
create table register (subjectId integer not null, studentId integer not null, score double precision, primary key (subjectId, studentId)) engine=InnoDB;
create table school (id integer not null, schoolDesc varchar(1000), name varchar(100) not null, primary key (id)) engine=InnoDB;
create table student (id integer not null, classId integer, mobile varchar(100), name varchar(100) not null, primary key (id)) engine=InnoDB;
create table subject (id integer not null, domain varchar(20), subjectDesc varchar(100), name varchar(100) not null, primary key (id)) engine=InnoDB;
drop table if exists class;
drop table if exists register;
drop table if exists school;
drop table if exists student;
drop table if exists subject;
create table class (id integer not null, code varchar(100) not null, classDesc varchar(1000), schoolId integer, primary key (id)) engine=InnoDB;
create table register (subjectId integer not null, studentId integer not null, score double precision, primary key (subjectId, studentId)) engine=InnoDB;
create table school (id integer not null, schoolDesc varchar(1000), name varchar(100) not null, primary key (id)) engine=InnoDB;
create table student (id integer not null, classId integer, mobile varchar(100), name varchar(100) not null, primary key (id)) engine=InnoDB;
create table subject (id integer not null, domain varchar(20), subjectDesc varchar(100), name varchar(100) not null, primary key (id)) engine=InnoDB;
